version: '3.1'

services:
  app:
    build: .
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      SQL_LITE_TESTS: ${SQL_LITE_TESTS}
    ports:
      - "5000:5000"
    networks:
      - app-network
  
networks:
  app-network:
    external: true

volumes:
  postgres_data: